qse_exact_file=true
qse_exact_query_based=false
qse_approximate_file=false
isWikiData=false
max_cardinality=true

dataset_name=DBpedia
expected_number_of_classes=500
expected_number_of_lines=50000000

dataset_path=/app/data/dbpedia.n3
resources_path=/app/qse/src/main/resources

# set to dbpedia/endpoint when qse_exact_query_based is set as true
# set to  dbpedia/sampled when qse_exact_query_based is set as true
output_file_path=/app/local/Output/dbpedia/default/

graphdb_url=http://172.0.0.0:7200
graphdb_repository=DBPEDIA


entity_sampling_threshold=500
entity_sampling_target_percentage=75

# this is to be set when qse_approximate_file is set as true. It should be the default directory inside the dataset name's directory
default_directory=/app/local/Output/dbpedia/default/
