qse_exact_file=true
qse_exact_query_based=false
qse_approximate_file=false
isWikiData=false
max_cardinality=true

dataset_path=/app/data/lubm.n3
resources_path=/app/qse/src/main/resources

# set to lubm/endpoint when qse_exact_query_based is set as true
# set to  lubm/sampled when qse_exact_query_based is set as true
output_file_path=/app/local/Output/lubm/default/

dataset_name=LUBM
expected_number_of_classes=25
expected_number_of_lines=167135019

# this is to be set when qse_approximate_file is set as true. It should be the default directory inside the dataset name's directory
default_directory=/app/local/Output/lubm/default/

entity_sampling_threshold=500
entity_sampling_target_percentage=75

graphdb_url=http://172.0.0.0:7200
graphdb_repository=LUBM