qse_exact_file=false
qse_exact_query_based=false
qse_approximate_file=true
isWikiData=true
max_cardinality=false

dataset_name=WikiData21
expected_number_of_classes=79301
expected_number_of_lines=500000000

dataset_path=/app/data/wdt21.n3
resources_path=/app/qse/src/main/resources

# set to wdt21/endpoint when qse_exact_query_based is set as true
# set to  wdt21/sampled when qse_exact_query_based is set as true
output_file_path=/app/local/Output/wdt21/default/

entity_sampling_threshold=500
entity_sampling_target_percentage=75

default_directory=/app/local/Output/wdt21/default/

graphdb_url=http://172.0.0.0:7200
graphdb_repository=WikiData21